[package]
name = "modules_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "module_bin"
path = "src/main.rs"

[lib]
name = "module_lib"
path = "src/lib/lib.rs"


